kind: pipeline
name: default

steps:
  - name: build
    image: circleci/ruby:2.6.5-node
    commands:
      - sudo rm config/database.yml
      - sudo mv config/database.yml.ci config/database.yml
      - sudo -E bundle install --path /bundle --without production,development
      - sudo -E bundle exec rails db:create RAILS_ENV=test
      - sudo -E bundle exec rails db:schema:load RAILS_ENV=test
      - sudo -E bundle exec rspec spec
    volumes:
      - name: gem-cache
        path: /bundle
      - name: tmp
        path: /drone/src/tmp
    environment:
      RAILS_ENV: test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      DATABASE_HOST: database
      PARALLEL_TEST_PROCESSORS: 15

services:
  - name: database
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: autostat_test

volumes:
  - name: gem-cache
    host:
      path: /tmp/cache
  - name: tmp
    temp: {}
