---
kind: pipeline
type: docker
name: default

steps:

  - name: restore
    image: plugins/s3-cache
    settings:
      pull: true
      access_key: 3R3u3XVKmNcPWCpzqV6R9vgtdgw6tk3Q
      secret_key:
        from_secret: minio
      endpoint: https://cache.love-foundation.org/
      root: https://cache.love-foundation.org/minio/cacherails
      restore: true


  - name: test
    image: circleci/ruby:2.6.5-node
    commands:
      - sudo rm config/database.yml
      - sudo mv config/database.yml.ci config/database.yml
      - sudo gem install bundler:2.1.4
      - sudo -E bundle config set path '/bundle'
      - sudo -E bundle config set without 'production,development'
      - sudo -E bundle install
      - sudo -E bundle exec rails db:create RAILS_ENV=test
      - sudo -E bundle exec rails db:schema:load RAILS_ENV=test
      - sudo -E bin/rails assets:precompile
      - sudo -E bundle exec rspec spec
    environment:
      RAILS_ENV: test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      DATABASE_HOST: database
      POSTGRES_DB: autostat_test
      PARALLEL_TEST_PROCESSORS: 15

  - name: rebuild
    image: plugins/s3-cache
    settings:
      pull: true
      endpoint: https://cache.love-foundation.org
      access_key: 3R3u3XVKmNcPWCpzqV6R9vgtdgw6tk3Q
      secret_key:
        from_secret: minio
      rebuild: true
      root: cacherails
      mount:
        - node_modules
        - bundle
      when:
        event: push

  - name: flush
    image: plugins/s3-cache:1
    settings:
      pull: true
      endpoint: https://cache.love-foundation.org
      access_key: 3R3u3XVKmNcPWCpzqV6R9vgtdgw6tk3Q
      secret_key:
        from_secret: minio
      flush: true
      flush_age: 14

services:
  - name: database
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: autostat_test
