---
kind: pipeline
type: docker
name: default

cache-common: &cache-common
  image: meltwater/drone-cache
  environment:
    PLUGIN_ACCESS_KEY: 3R3u3XVKmNcPWCpzqV6R9vgtdgw6tk3Q
    PLUGIN_SECRET_KEY:
      from_secret: minio
  pull: true

cache-settings: &cache-settings
  bucket: cache
  region: main
  path_style: true
  endpoint: https://cache.love-foundation.org
  mount:
    - 'node_modules'
    - 'bundle'

steps:
  - name: restore-cache
    <<: *cache-common
    settings:
      <<: *cache-settings
      restore: true


  - name: build
    image: circleci/ruby:2.6.5-node
    commands:
      - sudo rm config/database.yml
      - sudo mv config/database.yml.ci config/database.yml
      - sudo gem install bundler:2.1.4
      - sudo -E bundle config set path '/bundle'
      - sudo -E bundle config set without 'production,development'
      - sudo -E bundle install
      - sudo -E bundle exec rails db:create RAILS_ENV=test
      - sudo -E bundle exec rails db:schema:load RAILS_ENV=test
      - sudo -E bin/rails assets:precompile
      - sudo -E bundle exec rspec spec
    environment:
      RAILS_ENV: test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      DATABASE_HOST: database
      POSTGRES_DB: autostat_test
      PARALLEL_TEST_PROCESSORS: 15

  - name: rebuild-cache
    <<: *cache-common
    settings:
      <<: *cache-settings
      rebuild: true

services:
  - name: database
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: autostat_test
