# docker-compose.yml
version: '3.0'
services:

  postgres:
    environment:
      POSTGRES_PASSWORD: postgres
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  web:
    environment:
      - WEBPACKER_DEV_SERVER_HOST=webpacker
      - DATABASE_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=lovebook_test
    build:
      context: .
      args:
        precompileassets: not
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - webpacker

  webpacker:
    build:
      context: .
      args:
        precompileassets: not
    command: ./bin/webpack-dev-server #./bin/webpack-dev-server
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3035:3035
    environment:
      - NODE_ENV=development
      - RAILS_ENV=development
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
      - WEBPACKER_DEV_SERVER_PORT=3035
